/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoccuemtQaIndexRouteImport } from './routes/doccuemt-qa/index'
import { Route as AiChatbotIndexRouteImport } from './routes/ai-chatbot/index'
import { Route as ApiDocuemtQaRouteImport } from './routes/api/docuemt-qa'
import { Route as ApiAiChatbotRouteImport } from './routes/api/ai-chatbot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoccuemtQaIndexRoute = DoccuemtQaIndexRouteImport.update({
  id: '/doccuemt-qa/',
  path: '/doccuemt-qa/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatbotIndexRoute = AiChatbotIndexRouteImport.update({
  id: '/ai-chatbot/',
  path: '/ai-chatbot/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocuemtQaRoute = ApiDocuemtQaRouteImport.update({
  id: '/api/docuemt-qa',
  path: '/api/docuemt-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatbotRoute = ApiAiChatbotRouteImport.update({
  id: '/api/ai-chatbot',
  path: '/api/ai-chatbot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ai-chatbot': typeof ApiAiChatbotRoute
  '/api/docuemt-qa': typeof ApiDocuemtQaRoute
  '/ai-chatbot/': typeof AiChatbotIndexRoute
  '/doccuemt-qa/': typeof DoccuemtQaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai-chatbot': typeof ApiAiChatbotRoute
  '/api/docuemt-qa': typeof ApiDocuemtQaRoute
  '/ai-chatbot': typeof AiChatbotIndexRoute
  '/doccuemt-qa': typeof DoccuemtQaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ai-chatbot': typeof ApiAiChatbotRoute
  '/api/docuemt-qa': typeof ApiDocuemtQaRoute
  '/ai-chatbot/': typeof AiChatbotIndexRoute
  '/doccuemt-qa/': typeof DoccuemtQaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/ai-chatbot'
    | '/api/docuemt-qa'
    | '/ai-chatbot/'
    | '/doccuemt-qa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/api/ai-chatbot' | '/api/docuemt-qa' | '/ai-chatbot' | '/doccuemt-qa'
  id:
    | '__root__'
    | '/'
    | '/api/ai-chatbot'
    | '/api/docuemt-qa'
    | '/ai-chatbot/'
    | '/doccuemt-qa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAiChatbotRoute: typeof ApiAiChatbotRoute
  ApiDocuemtQaRoute: typeof ApiDocuemtQaRoute
  AiChatbotIndexRoute: typeof AiChatbotIndexRoute
  DoccuemtQaIndexRoute: typeof DoccuemtQaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doccuemt-qa/': {
      id: '/doccuemt-qa/'
      path: '/doccuemt-qa'
      fullPath: '/doccuemt-qa/'
      preLoaderRoute: typeof DoccuemtQaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chatbot/': {
      id: '/ai-chatbot/'
      path: '/ai-chatbot'
      fullPath: '/ai-chatbot/'
      preLoaderRoute: typeof AiChatbotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docuemt-qa': {
      id: '/api/docuemt-qa'
      path: '/api/docuemt-qa'
      fullPath: '/api/docuemt-qa'
      preLoaderRoute: typeof ApiDocuemtQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chatbot': {
      id: '/api/ai-chatbot'
      path: '/api/ai-chatbot'
      fullPath: '/api/ai-chatbot'
      preLoaderRoute: typeof ApiAiChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAiChatbotRoute: ApiAiChatbotRoute,
  ApiDocuemtQaRoute: ApiDocuemtQaRoute,
  AiChatbotIndexRoute: AiChatbotIndexRoute,
  DoccuemtQaIndexRoute: DoccuemtQaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
